### ISSUE TITLE
Reproducing result of multilingual train.

### ISSUE THREAD

**Issue by alexc-l** [csebuetnlp/xl-sum#11]
Hi.
Congratulations on your work first of all. I'd like to reproduce your result on the multilingual training process. And I have several questions:
1. Does the hyperparameters in the file "distribution_train.sh" are the actual parameters you implemented? 
2. Were all the languages in your dataset used in the training? 
3. Besides, if I want to shift the parameter "max_steps" into "num_train_epochs", what it should be, like 10 or more?
Thank you ahead!

**Comment by abhik1505040** [comment]
Hi, thanks for appreciating our work! We are happy to answer your questions:

1. Yes. We used the hyperparameters in [distributed_trainer.sh](https://github.com/csebuetnlp/xl-sum/blob/master/seq2seq/distributed_trainer.sh) with [this SLURM job script](https://github.com/csebuetnlp/xl-sum/blob/master/seq2seq/job.sh) on a cluster of 8 GPUs. Note that, the effective batch size of our setup is 256. You should update `PER_DEVICE_TRAIN_BATCH_SIZE` and `gradient_accumulation_steps` according to the number of GPUs you use to maintain this effective batch size.
 
2.  Yes, all 45 languages were used in multilingual training.

3.  As we used a smoothing factor to sample batches from different languages during training, we recommend using `max_steps` to estimate the number of epochs that each language will receive. Nonetheless, to answer your initial question, if you want to replicate our 50k training steps using `num_train_epochs`, you would need to set it to approximately 235. This number is higher than usual since we defined the total dataset length as the sum of individual language-wise dataset lengths weighted by their respective sampling factors.

**Comment by alexc-l** [comment]
Hi, Thank you so much for the response! I do have an additional question though.

Assume I want to put training data from different languages separately into the model, if I want to make my experiment comparable to your baseline, which hyperparameters should I change? And which features should I consider (like the length of the dataset from a certain language or something else)?

To my understanding, the ”effective batch size“ should remain the same, and the number of epochs will change according to the length of the total dataset and the effective batch size. Then I should change the max_step parameter according to the total proportion of my total dataset length.

My premise is based on the following calculation: Your max_steps is 50k, and the approximate number of epochs is 235, then each epoch the model should go through 50k/235=212.8 steps. Since the model normally goes over the whole data in one epoch, then the total data points should be 212.8*256=54,476. And for each language, there is a sampling probability to control how much data to contribute to the total data points.

Therefore I should figure out the sampling probabilities of the dataset I intend to use (which is not all 45) and calculate the max_step following the aforementioned path. Finally, even though I inject the dataset in different epochs, I should set the max_steps beforehand to make the experiment comparable to yours. Is this the right thing to do?

I'm so sorry to bother you again and truly grateful for your help!
Looking forward to your reply!
________________________________

**Comment by abhik1505040** [comment]
@alexc-l 

> Assume I want to put training data from different languages separately into the model
> Finally, even though I inject the dataset in different epochs,

I am not sure what you meant by these two lines. However, from the rest of the message, I'm assuming you are not looking to modify the training pipeline in any way and inquiring about reasonable hyperparameter choices for replicating our multilingual training with a subset of the 45 languages. 

Regarding the calculations you provided, as I explained before, the overall dataset is a mixture of different language-wise datasets with a smoothing factor to control the sampling probabilities. As such, by the time the model consumes all data points of a high-resource language once, there could have been multiple passes over a low-resource language. Therefore, the notion of an epoch over the entire dataset is neither clear nor useful. Please see the following snippet or the `MultiDataset` class here to understand better how this works.

https://github.com/csebuetnlp/xl-sum/blob/6b6da9eb052060724e9ffb17d18c291e8c61b553/seq2seq/utils.py#L162-L172

Even if you plan to leave out some languages, 50k training steps with 0.5 as the `upsampling_factor` are reasonable hyperparameter choices. But, of course, you'd need to pick the best model by evaluating some of the earlier checkpoints as well.

**Comment by alexc-l** [comment]
Hi, I understand the design behind. Thank you so much! It was very helpful! And I'll close the issue for no further questions.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
