### ISSUE TITLE
when the text is very short

### ISSUE THREAD

**Issue by 08tjlys** [csebuetnlp/xl-sum#4]
hi,
   first of all, really thanks for such great project.
   When i tried your inference code on hugging face, i found that when the text is short, for example like just "weather is fine", it will generate a longer unrelated summary.
   i am totally new to summarization, so is there any thing i should pay attention to in such case? for example, in such case, generating inputs_ids will be different?
  really appreciate your guide if possible, thanks!

**Comment by Tahmid04** [comment]
Hi, thanks for appreciating our work. Since XL-Sum is a news article-summary dataset, models pretrained on it are  expected to generate news-like summaries, even when the input is not from the news domain, e.g., paper abstracts, and for your case non-article inputs. If you want to generate summaries for non-news inputs, we recommend you further fine-tune the model checkpoint on such data. And if you just want to reduce the output length, using a higher length penalty may suit your use case. Hope that helps!

**Comment by 08tjlys** [comment]
thanks a lot, it really helps
