### ISSUE TITLE
TypeError when using RougeScorer

### ISSUE THREAD

**Issue by sarakolding** [csebuetnlp/xl-sum#7]
When I try to run  `scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True , lang='danish')` I get the following error:
`TypeError: __init__() got an unexpected keyword argument 'lang'`

**Comment by abhik1505040** [comment]
Hi, It looks like the `multilingual_rouge_scoring` package wasn't installed correctly. If you are installing the required dependencies from [this](https://github.com/csebuetnlp/xl-sum/tree/master/seq2seq) page, make sure you execute [this](https://github.com/csebuetnlp/xl-sum/blob/master/seq2seq/setup.sh) script via `bash setup.sh` first. Otherwise, reinstall the package using the commands mentioned [here](https://github.com/csebuetnlp/xl-sum/tree/master/multilingual_rouge_scoring#setup). This should fix the issue.

**Comment by sarakolding** [comment]
That worked, thank you!
