### ISSUE TITLE
Slow inference using HF checkpoint 

### ISSUE THREAD

**Issue by meharbhatia** [csebuetnlp/xl-sum#9]
Is there any way to speed up the inference time of your HF checkpoint mt5 model?

**Comment by Tahmid04** [comment]
Hi, the issue is actually with the pretraiend model (mT5) used. mT5 does not support FP16 training/inference and throws NaNs. So, we have no option but to use FP32 for training/inference, making them slow in the process. You can have a look at [this issue](https://github.com/huggingface/transformers/issues/10819) for more clarification.
